# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ead39a1ae06d62fc84f7278d2a84d501298da26bd4fc884a0091f527474c736070fa7991a83cf14f0ed9dbfea60070596650bd8cddc67688fe2adad46566587

test:
  secret_key_base: c4383e7d60ecbe4bf188017709e34135a4e27be7dac00c149843182f78dc376b3dc0f860eedcb38b350d0ffddf5298c915888bac2c43ff73865ce2a674af89d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
